// in the real world these would probably be autogenerated protobufs
package view

import "time"

// User are the values returned for a given user that is returned
type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// UserUpdate is the payload used to update a user
type UserUpdate struct {
	Name string `json:"name"`
}
